PostgreSQL:
  restart: always
  image: threew82/postgres:9.6-1
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=postgres
    - DB_PASS=
    - DB_NAME=
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
